### PR TITLE
Fix azlyrics fetcher

### PR DESCRIPTION
**Pull request by paul70011**
Fixes issue #543.

### CODE REVIEW

**Comment by Eolien55** [comment]
I don't really see this as a fix. The problem is that the way lyrics are obtained is more obfuscated than before (usage of an API instead of plain text). Or maybe the change from the `div` to the comment you provided _actually_ permits to obtain the lyrics ?

**Comment by Eolien55** [comment]
Well, it seems that you were right : they changed their HTML. I tried getting the lyrics with `curl`, and saw nothing that seemed to be about lyrics. I just assumed the site decided to use an API, but I was wrong (I just needed to set the User Agent for it to work). So this DOES fix the issue

**Comment by paul70011** [comment]
@charlie39 
This works for me:
`lyrics_fetchers = musixmatch, sing365, metrolyrics, justsomelyrics, jahlyrics, plyrics, tekstowo, zeneszoveg, internet`

Don't forget the 's' at the end: lyrics_fetcher**s**.

**Comment by arybczak** [comment]
I can't test that fix right now. Does it fix the problem? You can verify by running `ncmpcpp --test-lyrics-fetchers`.

**Comment by paul70011** [comment]
`ncmpcpp --test-lyrics-fetchers` returns ok for azlyrics.com with and without the fix.
This fixes the empty text being returned by the fetcher.
Maybe someone else can also compile and confirm it?

**Comment by charlie39** [comment]
ok my problem was i haven't updated the config file for a while so i still had lyricsmania
and lyricwiki ( which, i found after going through the git log, were removed
somewhere in 2020) on ```lyrics_fetchers``` so uncommenting it always gives me error.
My bad.

Yeah i compiled and tested this commit and it has fixed the issue with azlyrics so i guess i don't have
tp rearrange anything now.

**Comment by charlie39** [comment]
> I can't test that fix right now. Does it fix the problem? You can verify by running `ncmpcpp --test-lyrics-fetchers`.

Yes, it fixed the problem for me

**Comment by charlie39** [comment]
Also, i have run the ```ncmpcpp --test-lyrics-fetchers``` multiple times and it
retains failed on metrolyrics.com. Checking the site, i could only find
metrolyrics.pro and not metrolyrics.com. Seems the site has changed the the
domain name from .com to .pro

**Comment by jeandestouches** [comment]
> `ncmpcpp --test-lyrics-fetchers` returns ok for azlyrics.com with and without the fix. This fixes the empty text being returned by the fetcher. Maybe someone else can also compile and confirm it?
Thanks paul70011! I can confirm the fix works fine on my Gentoo system. Before that, it only returned empty text.

**Pull request closed without merging**
