### PR TITLE
Improve specrum visulaizer for transparent backgrounds

### PR DESCRIPTION
**Pull request by TilCreator**
I replaced the previous flipping method with chars I found in [Symbols for Legacy Computing](https://unicode.org/charts/PDF/U1FB00.pdf). This improves the spectrum visualizer when viewed in a terminal with a transparent background.

old:
screenshot_1617751540
new:
screenshot_1617751531
(Both tested in kitty)

### CODE REVIEW

**Comment by arybczak** [comment]
Thanks. Sadly, that doesn't seem to look good in my terminal (konsole) :(

Screenshot_20210408_225258

**Comment by TilCreator** [comment]
I guess that depends on the font and renderer, on termux (Android app) he whole visualizer looks bad. Maybe try another font (font config should also be able to only replace the legacy computing chars)?
I will add a config option to enable / disable the legacy chars with an appropriate "warning", should it be enabled or disabled by default?

**Comment by coothon** [comment]
Is there any reason this wasn't merged beside the author's typos? It's behind an option, as far as I can tell, and fixes (in some cases) an ugly hack in the visualizer; and if it doesn't, just disable it.

It merged to master without issue for me, and works great with my font. Does no one else want this feature?

**Comment by TilCreator** [comment]
I should maybe fix the typos ^^

I'm using #467 and  #482 on the newest release for as long as I wrote them without issue.

**Comment by arybczak** [comment]
Looks like this works fine in konsole now, so let's merge. Thanks!

**Pull request merged**
